### ISSUE TITLE
When you released the code !

### ISSUE THREAD

**Issue by jiaaihhy** [huawei-noah/Pretrained-IPT#1]
Dear noah ：
Thank you very much for your work！I looked at your paper and was struck by the beauty of it！
I want to know When you will released the code!
THANK YOU!

**Comment by amiltonwong** [comment]
Also waiting for the code release +1

**Comment by GuideWsp** [comment]
+1

**Comment by splinter21** [comment]
+4

**Comment by Shaw95** [comment]
> Dear noah ：
> Thank you very much for your work！I looked at your paper and was struck by the beauty of it！
> I want to know When you will released the code!
> THANK YOU!

Thanks for your attention. Code will be released soon.

**Comment by Shaw95** [comment]
> Dear noah ：
> Thank you very much for your work！I looked at your paper and was struck by the beauty of it！
> I want to know When you will released the code!
> THANK YOU!

We have already released our MindSpore code.  You can refer to https://gitee.com/mindspore/mindspore/tree/master/model_zoo/research/cv/IPT

**Comment by splinter21** [comment]
Waiting for pytorch version!

**Comment by joaocps** [comment]
+1

**Comment by Dpw506** [comment]
+1
