### ISSUE TITLE
pytorch training code

### ISSUE THREAD

**Issue by ryanlu2240** [huawei-noah/Pretrained-IPT#10]
will future update add pytorch training code?

**Comment by jiaaihhy** [comment]
I want too， why dont have train code! I hope you release train code soon ! thank you

**Comment by Shaw95** [comment]
> I want too， why dont have train code! I hope you release train code soon ! thank you
> will future update add pytorch training code?

Currently, we don't have a plan to release the training code. Please refer to our MindSpore version, which released the complele code of IPT. Thank you

**Comment by ryanlu2240** [comment]
One more question, can you provide ImageNet pytorch pretrain weight 
I may try to implement the training part, it will be really helpful if you can provide the pytorch ImageNet pretrain weight. Thank you

**Comment by Shaw95** [comment]
> One more question, can you provide ImageNet pytorch pretrain weight
> I may try to implement the training part, it will be really helpful if you can provide the pytorch ImageNet pretrain weight. Thank you

Fine, we have uploaded it.
