### ISSUE TITLE
Dataset links

### ISSUE THREAD

**Issue by cmhungsteve** [huawei-noah/Pretrained-IPT#11]
Thank you for sharing this great repo!

I found that some links about datasets are not valid now.
And some links are directed to some project pages, instead of downloadable links?

It would be great if you can update the links and let users directly download the datasets from those links.
Thank you.

**Comment by HantingChen** [comment]
Sorry for the inconvenience. Due to some authority reasons, we cannot share the directly downloadable links. You may found these dataset on other repositories, such as:
http://vllab.ucmerced.edu/wlai24/LapSRN/

**Comment by cmhungsteve** [comment]
Got it. Thank you.
