### ISSUE TITLE
NameError: name 'model' is not defined

### ISSUE THREAD

**Issue by amateurbo** [huawei-noah/Pretrained-IPT#16]
When I enter “python main.py --dir_data datasets --pretrain models --data_test Set5+Set14+B100+Urban100 --scale 2+3+4”
The following error occurs:

Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 24, in main
    _model = model.Model(args, checkpoint)
NameError: name 'model' is not defined

What is the reason for this? How to solve it?

**Comment by HantingChen** [comment]
Thanks for the feedback. We have fixed the bug.
