### ISSUE TITLE
How to use this model for denosing.

### ISSUE THREAD

**Issue by abood002** [huawei-noah/Pretrained-IPT#17]
Hello,
Sorry for the beginner question but I couldn't figure out how to use the trained model for denoising.
I have downloaded the pre-trained model "IPT_denoise50.pt" and the dataset "CBSD68", I have moved the model for the "model" folder and the images with noise to the "DIV2K_train_HR" folder. After running the "main.py" code I got a list of .py files in the "bin" folder but no denoised image.
Thanks in advance.

**Comment by HantingChen** [comment]
Hi, could you please provide the output in command lines after running the code?
