### ISSUE TITLE
How can I train/fine-tune the modle in new dataset?

### ISSUE THREAD

**Issue by abood002** [huawei-noah/Pretrained-IPT#21]
Hello,
Thanks for sharing your great work.
It is not clear to me how we can train or fine-tune this model in a new dataset.
Thanks in advance.

**Comment by HantingChen** [comment]
We only release evaluation code here. You may refer to mindspore code for training (https://gitee.com/mindspore/mindspore/tree/master/model_zoo/research/cv/IPT )

**Comment by abood002** [comment]
Hello HantingChen,
Thanks for your reply.
I have tried visiting the link you provided but it gives me "Error 404 page not found"
