### ISSUE TITLE
Some question about the mindspore code different from paper

### ISSUE THREAD

**Issue by jiaaihhy** [huawei-noah/Pretrained-IPT#3]
Dear noah:
In your IPT paper, writer that " The body has 12 encoder layers and 12 decoder layers.", but in the mindspore code, the num_layers in encoder and decoder all 4 layers, should change 4 to 12? or 4?
Looking forward your reply

**Comment by HantingChen** [comment]
The num_layers should be changed to 12. Note that the mindspore code is a 4 layers demo.
