### ISSUE TITLE
重新训练时，图像尺寸与代码提供的尺寸不一致，该如何调整相关超参数？

### ISSUE THREAD

**Issue by CCECfgd** [huawei-noah/Pretrained-IPT#31]
作者提供的代码示例为48*48*3，当我使用256*256*3的图像重新进行训练时，该调整那些超参数，以及调整为多少？期待作者的解答。

**Comment by HantingChen** [comment]
你好，可以采用 --patch_size 256 --patch_dim 8 --n_feats 9进行超参数调整
