### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 118.00 MiB (GPU 0; 2.00 GiB total capacity; 1.19 GiB already allocated; 0 bytes free; 1.27 GiB reserved  in total by PyTorch)

### ISSUE THREAD

**Issue by oneonejia** [huawei-noah/Pretrained-IPT#33]
输入python main.py --dir_data test_data --pretrain model/IPT_sr2.pt --data_test Set5 --scale 1
出现了
Making model...
Preparing loss function:
1.000 * L1
Evaluation:
  0%|                                                     | 0/5 [00:00<?, ?it/s]
RuntimeError: CUDA out of memory. Tried to allocate 118.00 MiB (GPU 0; 2.00 GiB total capacity; 1.19 GiB already allocated; 0 bytes free; 1.27 GiB reserved
 in total by PyTorch)
但是只有一个显卡，该怎么处理呢

**Comment by HantingChen** [comment]
请尝试减少--crop_batch_size
