### ISSUE TITLE
train

### ISSUE THREAD

**Issue by Avicill-echo** [huawei-noah/Pretrained-IPT#46]
感谢您提供的开源代码，您的代码可以重新训练么？

**Comment by HantingChen** [comment]
You can refer to https://gitee.com/mindspore/models/tree/master/research/cv/IPT. Thanks!

**Comment by Avicill-echo** [comment]
Thanks~





------------------ Original ------------------
From: HantingChen ***@***.***&gt;
Date: Thu,Jul 28,2022 11:31 AM
To: huawei-noah/Pretrained-IPT ***@***.***&gt;
Cc: mu chang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [huawei-noah/Pretrained-IPT] train (Issue #46)
