### ISSUE TITLE
Question of task embedding

### ISSUE THREAD

**Issue by mrluin** [huawei-noah/Pretrained-IPT#53]
Hello, 

Thanks for your works!

In your paper, one learnable task embedding is added before decoding, but i cannot find the implementation in your code. Could you please help me how the task embedding works in your work, thanks!

**Comment by hyunW3** [comment]
learnable task embedding which you ask might be this one. (In ipy.py file)
https://github.com/huawei-noah/Pretrained-IPT/blob/675540ed09169709e3603e9872fd13d238cbbe27/model/ipt.py#L115
https://github.com/huawei-noah/Pretrained-IPT/blob/675540ed09169709e3603e9872fd13d238cbbe27/model/ipt.py#L142
